version: '3.8'
services:



    users:
        build: userprofile
        ports:
        - 8000:8000
    products:
        build: product
        ports:
        - 8009:8009

    ordercrud:
        build: ordercrud
        ports:
        - 8001:8001

    orderfilter:
        build: orderfilter
        ports:
        - 8004:8004

    reviews:
        build: review
        ports:
        - 8020:8020

    deliveryagent:
        build: deliveryservice
        ports:
        - 3333:3333  